ALTER TABLE users ADD COLUMN IF NOT EXISTS allowed_departments TEXT[] DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS can_bulk_move BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS can_bulk_copy BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS can_bulk_delete BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS can_bulk_rename BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS can_bulk_download BOOLEAN DEFAULT TRUE;
